### ISSUE TITLE
Problem launching DrawerApp

### ISSUE THREAD

**Issue by sebkur** [dlsc-software-consulting-gmbh/GemsFX#18]
When I run the DrawerApp like this:

    mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.DrawerApp

I get lots of errors after clicking the "Show Drawer" button.

Output repeats the following error message:

    java.lang.NoSuchMethodError: 'void com.sun.prism.Graphics.setPerspectiveTransform(com.sun.javafx.geom.transform.GeneralTransform3D)'
        at javafx.web/com.sun.javafx.webkit.prism.WCGraphicsPrismContext$ContextState.apply(WCGraphicsPrismContext.java:1224)
        at javafx.web/com.sun.javafx.webkit.prism.WCGraphicsPrismContext.getGraphics(WCGraphicsPrismContext.java:136)
        at javafx.web/com.sun.javafx.webkit.prism.WCGraphicsPrismContext.getPlatformGraphics(WCGraphicsPrismContext.java:126)
        at javafx.web/com.sun.javafx.webkit.prism.WCPageBackBufferImpl.flush(WCPageBackBufferImpl.java:71)
        at javafx.web/com.sun.webkit.WebPage.paint(WebPage.java:708)
        at javafx.web/com.sun.javafx.sg.prism.web.NGWebView.renderContent(NGWebView.java:95)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
        at javafx.graphics/com.sun.javafx.sg.prism.NodeEffectInput.getImageDataForBoundedNode(NodeEffectInput.java:237)
        at javafx.graphics/com.sun.javafx.sg.prism.NodeEffectInput.filter(NodeEffectInput.java:131)
        at javafx.graphics/com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:185)
        at javafx.graphics/com.sun.scenario.effect.Offset.filter(Offset.java:160)
        at javafx.graphics/com.sun.scenario.effect.Merge.filter(Merge.java:148)
        at javafx.graphics/com.sun.scenario.effect.DelegateEffect.filter(DelegateEffect.java:70)
        at javafx.graphics/com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
        at javafx.graphics/com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2384)
        at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(CacheFilter.java:685)
        at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.render(CacheFilter.java:587)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderCached(NGNode.java:2377)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2063)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
        at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:328)
        at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:834)

Any ideas?

**Comment by sebkur** [comment]
`java -version`:

    openjdk version "11.0.6" 2020-01-14
    OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
    OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode)

**Comment by sebkur** [comment]
Same problem occurs when I run from IntelliJ

**Comment by dlemmermann** [comment]
No idea what's going on here. This seems to be related to your setup and not the component. Closing this issue.
