### ISSUE TITLE
jdk15 JFX15 Exception

### ISSUE THREAD

**Issue by Hugolarson** [dlsc-software-consulting-gmbh/GemsFX#22]
Hello,
I get this exception

20-11-13 13:10:23| [JavaFX Application Thread|]:advit.log.LoggerHelper uncaughtException JavaFX Application Thread 
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at com.dlsc.gemsfx.keyboard.KeyboardView.loadKeyboard(KeyboardView.java:187)
	at com.dlsc.gemsfx.keyboard.KeyboardView.loadKeyboard(KeyboardView.java:168)
	at com.dlsc.gemsfx.keyboard.KeyboardView.loadKeyboard(KeyboardView.java:159)
	at com.dlsc.gemsfx.keyboard.KeyboardView.<init>(KeyboardView.java:122)

**Comment by dlemmermann** [comment]
Then there is stuff missing on your classpath. Impossible for me to tell you what to do because I do not know your setup. But the pom.xml file of GemsFX will tell you what is required.

**Comment by dlemmermann** [comment]
This issue is not relevant for this project because a) the keyboard has been moved into its own project called "KeyboardFX" and b) the bug is inside another project / codebase.
