### ISSUE TITLE
SearchField - commit gets called 3 times when an item is selected

### ISSUE THREAD

**Issue by larochef** [dlsc-software-consulting-gmbh/GemsFX#60]
I'm beginning to use the search field overriding the commit method to know when to trigger some action, and I was surprised to see the commit method being called 3 times everytime a change occurs.

After some debugging, here are the different places calling the commit method:

```
	at com.dlsc.gemsfx.SearchField.select(SearchField.java:400)
	at com.dlsc.gemsfx.skins.SearchFieldPopupSkin.selectItem(SearchFieldPopupSkin.java:122)
	at com.dlsc.gemsfx.skins.SearchFieldPopupSkin.lambda$registerEventListener$3(SearchFieldPopupSkin.java:101)
```

```
	at com.dlsc.gemsfx.skins.SearchFieldPopupSkin.selectItem(SearchFieldPopupSkin.java:123)
	at com.dlsc.gemsfx.skins.SearchFieldPopupSkin.lambda$registerEventListener$3(SearchFieldPopupSkin.java:101)
```

```
	at com.dlsc.gemsfx.SearchField.lambda$new$1(SearchField.java:93)
```

I only included the stack elements from gemfx, if more stack trace is needed I can provide more.

The first point I saw is that `SearchFieldPopupSkin.selectItem` calls commit and calls `SearchField.select` which also calls commit, so I guess the one in the `SearchFieldPopupSkin` could be removed safely.

For the last one it doesn't seem as obvious, I guess one comes from the hit of the `enter` key and the other one is triggered by the selection.

**Comment by dlemmermann** [comment]
Applications can now set an "onCommit" handler on SearchField.
